sensor:
  - platform: sht3xd
    # SHT30 https://esphome.io/components/sensor/sht3xd.html
    temperature:
      name: "Temperature"
      id: temperature
      disabled_by_default: true
    humidity:
      name: "Humidity"
      id: humidity
      disabled_by_default: true
    address: 0x44
